name: deployment

on:
  push:
    branches:
      - prod

jobs:
  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous redundant Builds
        uses: styfle/cancel-workflow-action@0.12
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4.0.1
        with:
          cache: 'npm'
          node-version: '18'
      - name: Install dependencies
        run: npm install --force
      - name: Run Build
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist


  test:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4.0.1
        with:
          cache: 'npm'
          node-version: '18'
      - name: Install dependencies
        run: npm install --force
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Run Test
        run: npm run test