name: deployment

on:
  push:
    branches:
      - prod

jobs:
  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous redundant Builds
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4.0.1
        with:
          cache: 'npm'
          node-version: '18'
      - name: Install dependencies
        run: npm install2 --force
      - name: Run Build
        run: npm run buildCI
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
      - name: Revertir commit en caso de fallo
        if: failure()
        uses: actions/undo-push@v1
        with:
          branch: prod

  test:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4.0.1
        with:
          cache: 'npm'
          node-version: '18'
      - name: Install dependencies
        run: npm install --force
      - uses: actions/download-artifact@v4.0.0
        with:
          name: build
          path: build
      - name: Run Test
        run: npm run testCI
      - name: Revertir commit en caso de fallo
        if: failure()
        uses: actions/undo-push@v1
        with:
          branch: prod